module.exports = [
  { size: [1600, 900] },
  { wait: 1800 },
  { eval: 'window.__RQ.start({ faction: "human", enemyFaction: "xeno", commander: "vanta", board: 0, difficulty: 1 }); "ok"' },
  { wait: 900 },
  { eval: 'window.__RQ.closeScreens(); "ok"' },
  { eval: 'window.__RQ.setGold(9000); window.__RQ.buildAll(); window.__RQ.startWave(); "built"' },
  { eval: 'window.__RQ.spawn("stockman", 3, 9); window.__RQ.spawn("brute", 1, 7); window.__RQ.step(2.5); "horde"' },
  { wait: 300 },
  { shot: 'r3-board' },
  { eval: 'window.__RQ.camera({ dist: 13, pitch: 0.55, yaw: 0.6 }); "cam1"' },
  { wait: 250 },
  { shot: 'r3-closeup' },
  { eval: 'window.__RQ.camera({ dist: 34, pitch: 0.95, yaw: 0.12 }); "cam2"' },
  { wait: 250 },
  { shot: 'r3-sky' },
  { eval: 'window.__RQ.camera({ dist: 15, pitch: 0.42, yaw: 1.1 }); "cam3"' },
  { wait: 250 },
  { shot: 'r3-angle' }
];
